pull_request_rules:
  - name: Automatic merge con CI pass
    conditions:
      - "check-success=ci/circleci: test"
      - "check-success=cypress: default-group"
      - "linear-history"
      - "author=dependabot"
    actions:
      merge:
        method: merge
